---
# defaults file for bifrost-deploy-nodes-dynamic
ironic_url: "http://localhost:6385/"
# Deprecated: nginx_port is no longer used and file_url_port should
# be used instead.
file_url_port: "{{ nginx_port | default('8080') }}"
network_interface: "virbr0"
ans_network_interface: "{{ network_interface | replace('-', '_') }}"
http_boot_folder: "/httpboot"
deploy_image_filename: "deployment_image.qcow2"
deploy_image: "{{http_boot_folder}}/{{deploy_image_filename}}"
inventory_dhcp: false
inventory_dhcp_static_ip: true
inventory_dns: false
deploy_url_protocol: "http"
noauth_mode: true
