---
init_template: systemd_template.j2
init_dest_dir: /etc/systemd/system/
ironic_bin_dir: /usr/local/bin/
init_ext: .service
syslinux_tftp_dir: /usr/lib/syslinux/
ipxe_dir: /usr/lib/ipxe/
sgabios_dir: /usr/share/qemu/
nginx_user: www-data
virt_group: libvirtd
mysql_service_name: mysql
required_packages:
  - mysql-server
  - dnsmasq
  - rabbitmq-server
  - python-dev
  - python-mysqldb
  - python-configparser
  - libffi-dev
  - libxslt1-dev
  - libssl-dev
  - libxml2-dev
  - ipxe
  - tftpd-hpa
  - tftp-hpa
  - syslinux-common
  - syslinux
  - xinetd
  - parted
  - ipmitool
  - psmisc
  - nginx
  - wget
  - genisoimage
  - kpartx
  - qemu-utils
  - python-openwsman
  - amtterm
  - sgabios
