---
init_template: systemd_template.j2
init_dest_dir: /usr/lib/systemd/system/
ironic_bin_dir: /usr/bin/
init_ext: .service
syslinux_tftp_dir: /var/lib/tftpboot
ipxe_dir: /usr/share/ipxe/
sgabios_dir: /usr/share/sgabios/
nginx_user: nginx
virt_group: libvirt
mysql_service_name: mariadb
required_packages:
  - mariadb-server
  - dnsmasq
  - rabbitmq-server
  - python-devel
  - MySQL-python
  - python-iniparse
  - libffi-devel
  - libxslt-devel
  - openssl-devel
  - libxml2-devel
  - ipxe-bootimgs
  - tftp-server
  - syslinux
  - syslinux-tftpboot
  - xinetd
  - parted
  - ipmitool
  - psmisc
  - nginx
  - wget
  - genisoimage
  - kpartx
  - qemu-kvm-tools
  - qemu-img
  - openwsman-python
  - sgabios-bin
# NOTE(cinerama): amtterm is not currently packaged for RHEL/CentOS 7.
